### ISSUE TITLE
commandline needs "--cap-default"

### ISSUE THREAD

**Issue by jd666** [mviereck/dockerfile-x11docker-mate#1]
When running with `podman` and `xpra` (`x11docker --podman --xpra --desktop --size 1400x900 x11docker/mate`)  `x11docker` builds a command line that includes `--cap-drop ALL` which causes the container startup to fail:
```
Error: container_linux.go:346: starting container process caused "apply caps: operation not permitted": OCI runtime permission denied error
```

When adding `--cap-default` to the startup the container launches successfully. (`x11docker --podman --xpra --cap-default --desktop --size 1400x900 x11docker/mate`)

**Comment by mviereck** [comment]
Thank you for reporting this!
I cannot reproduce the issue here.

What is your podman version? Here it is `podman version 2.0.4`.
What is your host system, maybe fedora? Here it is Debian bullseye.

For reference, the x11docker podman ticket is: https://github.com/mviereck/x11docker/issues/255
